### ISSUE TITLE
Does this library supports Table with Json fields too. ??

### ISSUE THREAD

**Issue by awemulya** [M1hacka/django-pg-bulk-update#57]
I have a Json column in my model.
Have anyone used this with json column.

ans = JSONField(default=dict)

**Comment by M1hacka** [comment]
Hi. 
Yes, I widely use library with HStore and JSONB and even HLL fields. Effective update of such fields (including concatenation) was one of this library initial goals for me.
First thing I want to ask is - what field do you use? Django and PostgreSQL of different versions have different JSONField implementations built on JSON or JSONB PostgreSQL types. Please, check this out (you can provide info about how you import it and what django version you have).
Do you have any trouble with it?

**Comment by awemulya** [comment]
from jsonfield import JSONField
django 1.8
postgres 9.5

**Comment by M1hacka** [comment]
Library should support it (it supports any django-built field), though I don't recommend you to use this kind of field.
If you look inside its implementation, it is inherited from `models.TextField` and stores data in PostgreSQL's TEXT type. As a result: 
1. You have to encode/decode every time on fetch/store/function calls occure which may be not effective in some cases with big data
2. You can't build indices on it
3. You can't use native PostgreSQL functions and operators for JSON and JSONB without type casts.

The only advantage of text type usage (though, JSON is still preferrable in this case) is saving a little bit of disk space.
It's better to use one of PostgreSQL native JSON or JSONB types. But Django introduced [JSONField](https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#jsonfield) support in 1.11 only. If you can update django - it will be better solution.

P. s. As TravisCI has limit on number of builds in OpenSource projects, I will support last 5 django, Python, PostgreSQL versions + some more. Previous versions may still work, but autotesting is disabled for them. You can see currently tested versions in [requirements section](https://github.com/M1hacka/django-pg-bulk-update#requirements).

**Comment by awemulya** [comment]
For older applications like django 1.8 Do you have any better alternatives tahn JSONFIELD from jsonfield library.

**Comment by M1hacka** [comment]
I haven't used any myself, so I can not be totally sure. I've found 2 libs imported like you have mentioned  as 'jsonfield' on pypi:
https://github.com/adamchainz/django-jsonfield
and
https://pypi.org/project/jsonfield/.
It looks like the first of them uses JSONB, while the second - TEXT types. Which one do you use?
